### ISSUE TITLE
使用时会类型转换异常 求问

### ISSUE THREAD

**Issue by Weidoudi** [hongyangAndroid/Highlight#17]
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.v7.internal.widget.ActionBarOverlayLayout$LayoutParams

**Comment by hongyangAndroid** [comment]
需要贴出完整的log信息，最好关联到某个类的某一行。

**Comment by Weidoudi** [comment]
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.v7.internal.widget.ActionBarOverlayLayout$LayoutParams
at android.support.v7.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:260)
at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:382)
at android.view.View.measure(View.java:18025)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
at android.view.View.measure(View.java:18025)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
at android.view.View.measure(View.java:18025)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2787)
at android.view.View.measure(View.java:18025)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2436)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1431)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1659)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1309)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6650)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
at android.view.Choreographer.doCallbacks(Choreographer.java:603)
at android.view.Choreographer.doFrame(Choreographer.java:572)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
t android.app.ActivityThread.main(ActivityThread.java:5741)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)

**Comment by hongyangAndroid** [comment]
以上log依然没有看出与Highlight的关联性。

**Comment by wangsai-silence** [comment]
ActionBarOverLayLayout的child应该是有特殊要求的，不能使用这种方案来对中间插入一个Framelayout
