### ISSUE TITLE
是不是不支持Fragment，我放在Fragment中有问题，如何破

### ISSUE THREAD

**Issue by yongchao1210** [hongyangAndroid/Highlight#65]
Process: com.zhy.highlight, PID: 14551
                                                                   java.lang.IllegalStateException: Could not find method clickKnown(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.widget.ImageView with id 'iv_known'
                                                                       at android.view.View$DeclaredOnClickListener.resolveMethod(View.java:4758)
                                                                       at android.view.View$DeclaredOnClickListener.onClick(View.java:4717)
                                                                       at android.view.View.performClick(View.java:5638)
                                                                       at android.view.View$PerformClick.run(View.java:22435)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6189)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:887)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)

**Comment by yongchao1210** [comment]
<ImageView
        android:id="@+id/iv_known"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/id_iv_tip"
        android:src="@drawable/jt_known"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="10dp"
        android:paddingRight="10dp"
        android:onClick="clickKnown"/>

onclick属性并不能用到fragment的xml里

**Comment by yongchao1210** [comment]
info_known.xml 文件中
ImageView
        android:id="@+id/iv_known"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/id_iv_tip"
        android:src="@drawable/jt_known"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="10dp"
        android:paddingRight="10dp"
        android:onClick="clickKnown"

android:onClick不能用在Fragment的xml中。。。
如何破。。。

**Comment by DuShuYuan** [comment]
mHightLight.getHightLightView().findViewById(R.id.iv_known).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    clickKnown();
                }
            });

这样写可以，你运行试试吧还会出其他问题，开始是空指针，你会解决的；弄好以后fragment来回切换还会出问题这个我也解决不了了

**Comment by DuShuYuan** [comment]
只能是在ativity里使用了。
在activity里拿到fragment的view就行了
有这个方法：
addHighLight(View view, int decorLayoutId, OnPosCallback onPosCallback, LightShape lightShape)

**Comment by chuzhonglingyan** [comment]
注入的点击事件clickKnown写到activity可行。
