### ISSUE TITLE
在fragment 中使用 显示正常， 但是切换页面的时候出现这个android.view.View.unFocus

### ISSUE THREAD

**Issue by initzf** [hongyangAndroid/Highlight#68]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
                                                                 at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4593)
                                                                 at android.view.ViewGroup.removeViewAt(ViewGroup.java:4555)
                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1540)
                                                                 at android.support.v4.app.BackStackRecord.executeOps(SourceFile:753)
                                                                 at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2363)
                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2149)
                                                                 at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(SourceFile:2103)
                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2013)
                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(SourceFile:710)
                                                                 at android.os.Handler.handleCallback(Handler.java:742)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:157)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5548)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:743)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)

请大神指点一下，谢谢。

**Comment by Cashdispenser** [comment]
.anchor(mActivity.findViewById(R.id.id_container))//如果是Activity上增加引导层，不需要设置anchor
那个id写上Activity的根布局的id就可以了

**Comment by wimwu** [comment]
anchor(mActivity.findViewById(R.id.id_container))添加后没有效果？还是有这个问题

**Comment by moyergo** [comment]
我也遇到了这个问题，要怎么解决呢？

**Comment by initzf** [comment]
@moyergo   抱歉啊， 我已经没有使用这个库了,换成其实方式实现了。

**Comment by jinshenglongsw** [comment]
> @moyergo 抱歉啊，我已经没有使用这个库了，换成其实方式实现了。

请问，您用了什么库解决的问题呢？
