### ISSUE TITLE
是我使用方法有问题吗？当我快速点击时 报错

### ISSUE THREAD

**Issue by zz371301632** [hongyangAndroid/Highlight#70]
compile 'com.isanwenyu.highlight:highlight:1.8.0'

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getHitRect(android.graphics.Rect)' on a null object reference
	at zhy.com.highlight.util.ViewUtils.getLocationInView(ViewUtils.java:42)
	at zhy.com.highlight.HighLight.updateInfo(HighLight.java:129)
	at zhy.com.highlight.view.HightLightView.buildMask(HightLightView.java:158)
	at zhy.com.highlight.view.HightLightView.onLayout(HightLightView.java:219)
	at android.view.View.layout(View.java:16121)
	at android.view.ViewGroup.layout(ViewGroup.java:5185)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16121)
	at android.view.ViewGroup.layout(ViewGroup.java:5185)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16121)
	at android.view.ViewGroup.layout(ViewGroup.java:5185)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16121)
	at android.view.ViewGroup.layout(ViewGroup.java:5185)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2532)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2226)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6686)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5879)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)

**Comment by uxnehciew** [comment]
请问问题解决了吗？
